#!/bin/bash
for i in `seq 0 50`
do
    if [ ! -f webtables/$(printf %02d $i).extracted ]; then
        rm -f webtables/$(printf %02d $i).tar
        rm -rf webtables/$i
        tar xvf webtables/$(printf %02d $i).tar.gz
        tar xvf webtables/$(printf %02d $i).tar
        touch webtables/$(printf %02d $i).extracted
    fi
done
